backend:
  name: git-gateway
  branch: main

media_folder: "uploads" # Where uploaded media files go in the repo
public_folder: "/uploads" # Where those files are served on the website

media_library:
  name: upload

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Hero Image", name: "hero", widget: "image", required: false }
